name: All

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - dedede

    steps:
    - name: github is annoying
      run: |
        git config --global url."https://${{ secrets.SUPERDUPERSECRET }}@github.com/".insteadOf https://github.com/

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.SUPERDUPERSECRET }}

    - name: run build
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo DEBUG=1 ./build_complete.sh ${{ matrix.board }} compress_img=1 quiet=1 distro=alpine release=edge

    - name: Upload built shim
      uses: softprops/action-gh-release@v2
      with:
        name: Shimboot ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        files: ./data/shimboot_${{ matrix.board }}.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
